package com.marcptr.cine.model.enums;

public enum ErrorCode {
    USER_NOT_FOUND,
    INVALID_REQUEST,
    LOGIN_ERROR,
    VALIDATION_ERROR,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    METHOD_NOT_ALLOWED,
    INVALID_JSON,
    ACCESS_DENIED,
    MISSING_PARAMETER,
    AUTHENTICATED_ERROR,
    TOKEN_INVALID,
    INVALID_URL, 
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXIST
}