spring.application.name=Cine
server.port=8080

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Cine

jwt.secret=084894c7d31418cee00e6958b1f63abf6ef192fb83d88ee3759ca7af4abfdf49
jwt.expiration=864000000
jwt.refresh-expiration=894000000
jwt.issuer=jhuoi

admin.username=Admin
admin.password=u8SDDu322asy8DA
admin.email=admin@admin.es

security.max_sessions=3
